export const transformFullJobDetails = (data) => {
  return {
    id: data.id,
    title: data.title,
    description: data.description,
    budgetCurrency: data.budget_currency,
    budgetAmount: data.budget_amount,
    budgetPayPeriod: data.budget_pay_period,
    country: data.country,
    city: data.city,
    address: data.address,
    jobCategories: data.job_category,
    isFullTime: data.is_full_time,
    isPartTime: data.is_part_time,
    hasContract: data.has_contract,
    contactEmail: data.contact_email || "",
    contactPhone: data.contact_phone || "",
    contactWhatsapp: data.contact_whatsapp || "",
    highestEducation: data.highest_education,
    languages: data.language,
    skills: data.skill,
    workingDays: data.working_days,
    status: data.status,
    applicant: data.applicant,
    createdAt: data.created,
    user: {
      id: data.user.id,
      name: data.user.name,
      email: data.user.email,
      countryCode: data.user.country_code,
      mobileNumber: data.user.mobile_number,
      image: data.user.image,
    },
    attachments: data.attachments.map((attachment) => ({
      id: attachment.id,
      path: attachment.path,
      type: attachment.type,
      title: attachment.title,
    })),
  };
};
